tytrip/trip/urls.py
from django.urls import path, register_converter
from . import views
from . import  converters
from .views import SearchResultsView, SignUpView, SignInView, log_out, PostDetailView, FeedBackView, SuccessView, \
    TagView

register_converter(converters.FourDigitYearConverter, "year4")

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    # path('about/', views.about, name='about'),
    # path('topics/<slug:topic_slug>/', views.TopicsListView.as_view(), name='topics'),
    path('addpage/', views.AddPage.as_view(), name='add_page'),
    # path('contact_old/', views.ContactFormView.as_view(), name='contact_old'),
    # path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    # path('tag/<slug:tag_slug>/', views.TagsListView.as_view(), name='tag'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(), name='edit_page'),
    path('delete/<slug:slug>/', views.DeletePage.as_view(), name='delete_page'),

    # path('signup/', SignUpView.as_view(), name='signup'),
    # path('signin/', SignInView.as_view(), name='signin'),
    # path('logout/', log_out, name='logout',),
    path('post/<slug>/', PostDetailView.as_view(), name='post_detail'),
    path('contact/', FeedBackView.as_view(), name='contact'),
    path('contact/success/', SuccessView.as_view(), name='success'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('tag/<slug:slug>/', TagView.as_view(), name="tag"),
]

tytrip/tytrip/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.decorators.cache import cache_page
from rest_framework import routers

from trip.sitemaps import PostSitemap
from trip.views import page_not_found, TripViewSet
from . import settings
from django.contrib.sitemaps.views import sitemap
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

sitemaps = {'posts': PostSitemap}

router = routers.SimpleRouter()
router.register(r'triplist', TripViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trip.urls')),
    path('users/', include('users.urls', namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),
    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Администрирование сайта tytrip.ru"

tytrip/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.messages import success
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='users:login'), name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view(template_name = "users/password_reset_form.html",
                                   email_template_name = "users/password_reset_email.html",
                                   success_url = reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                                                              success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    ]

tytrip/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True, null=True, verbose_name="Фотография")
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name="Дата рождения")

tytrip/users/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label='Логин',
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'class': "form-control",
            'id': "inputUsername",
        })
    )
    password = forms.CharField(
        label='Пароль',
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': "form-control mt-2",
            'id': "inputPassword",
        })
    )
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    # username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'class': "form-control",
            'id': "inputUsername",
            'type': 'username',
            'placeholder': 'Имя пользователя'
        }),
    )
    # password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': "form-control",
            'id': "inputPassword",
            'type': 'password',
            'placeholder': 'Пароль'
        }),
    )

    # password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': "form-control",
            'id': "ReInputPassword",
            'type': 'password',
            'placeholder': 'Повторите пароль'
        }),
    )
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        # labels = {
        #     'email': 'E-mail',
        #     'first_name': 'Имя',
        #     'last_name': 'Фамилия',
        # }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e-mail'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'first_name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'last_name'}),
        }


    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))
    this_year = datetime.date.today().year
    date_birth = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(this_year - 100, this_year - 5))))

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'date_birth', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

tytrip/users/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from tytrip import settings
from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


# Create your views here.
class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': "Авторизация"}

    # def get_success_url(self):
    #     return reverse_lazy('home') # LOGIN_REDIRECT_URL = 'home' in settings.py

class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': "Регистрация"}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    # model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': "Профиль пользователя", 'default_image': settings.DEFAULT_USER_IMAGE}
    success_url = reverse_lazy('users:profile')

    # def get_success_url(self):
    #     return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"
    extra_context = {'title': "Изменение пароля"}


####################### func_views ######################################
# def login_user(request):
#     if request.method == 'POST':
#         form = LoginUserForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user and user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('home'))
#     else:
#         form = LoginUserForm()
#     return render(request, 'users/login.html', {'form': form})


# def logout_user(request):
#     logout(request)
#     return HttpResponseRedirect(reverse('users:login'))
#
# def register(request):
#     if request.method == "POST":
#         form = RegisterUserForm(request.POST)
#         if form.is_valid():
#             user = form.save(commit=False)  # создание объекта без сохранения в БД
#             user.set_password(form.cleaned_data['password'])
#             user.save()
#             return render(request, 'users/register_done.html')
#     else:
#         form = RegisterUserForm()
#     return render(request, 'users/register.html', {'form': form})

tytrip/users/templates/users/login.html
{% extends 'base_new.html' %}
{% block title %}{{ title }}{% endblock %}

{% block header %}
    {% include 'trip/includes/header_new.html' %}
{% endblock %}
 
{% block content %}
<section class="my-registration-form">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <!--    ЭТО ХЛЕБНЫЕ КРОШКИ -->
                    <nav aria-label="breadcrumb" class="my-4">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Форма авторизации</li>
                        </ol>
                    </nav>

                    <div class="row justify-content-center">
                        <div class="col-6">
                            <p class="lead">Для входа укажите логин или email и пароль</p>
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <form method="post" action="{% url 'users:login' %}">
                                {% csrf_token %}
                                <input type="hidden" name="next" value="{{ next }}" />
                                <div class="mb-3">
                                    <label for="inputUsername" class="form-label visually-hidden">Имя пользователя</label>
                                    {{ form.username }}
                                </div>
                                <div class="mb-3">
                                    <label for="inputPassword" class="form-label visually-hidden">Пароль</label>
                                    {{ form.password }}
                                </div>
                                <button type="submit" class="btn btn-primary">Войти</button>
                            </form>
                        </div>
                        <p ><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
                        <br>
                        <hr>
                        <br>
                        <p>Другие способы входа</p>
                        <p>
                            <a class="poster-mini" href="{% url 'social:begin' 'github' %}"><img src="/media/social-auth/github.png"></a>
                            <a class="poster-mini" href="{% url 'social:begin' 'vk-oauth2' %}"><img src="/media/social-auth/vk.png"></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
</section>
{% endblock %}

tytrip/users/templates/users/password_change_done.html
{% extends 'base_new.html' %}
 
{% block content %}

<h1>Пароль успешно изменен!</h1>
 
<p >Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>

{% endblock %}

tytrip/users/templates/users/password_change_form.html
{% extends 'base_new.html' %}
 
{% block content %}
<div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="row justify-content-center">
                        <div class="col-6">
<h1>Изменение пароля</h1>
 
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="md-form mb-0" for="{{ f.id_for_label }}">{{f.label}}: </label> {{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    <br>
    {% endfor %}
 
    <p ><button type="submit" class="btn btn-primary">Изменить пароль</button></p>
</form>
</div>
</div>
                </div>
            </div>
</div>
{% endblock %}

tytrip/users/templates/users/password_reset_complete.html
{% extends 'base_new.html' %}
 
{% block content %}

<h1>Пароль изменен</h1>
 
<p >Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>

{% endblock %}

tytrip/users/templates/users/password_reset_confirm.html
{% extends 'base_new.html' %}
 
{% block content %}

<h1>Новый пароль</h1>
 
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
 
    <p ><button type="submit">Сохранить</button></p>
</form>


{% endblock %}

tytrip/users/templates/users/password_reset_done.html
{% extends "base_new.html" %}
{% load i18n %}
 
{% block content %}

<h1>Сброс пароля</h1>
<p >{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
<p >{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

tytrip/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

tytrip/users/templates/users/password_reset_form.html
{% extends 'base_new.html' %}
 
{% block content %}

<div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="row justify-content-center">
                        <div class="col-6">
<h1>Восстановление пароля</h1>
 
<form method="post">
    {% csrf_token %}
    {% for f in form %}
    <div class="mb-3">
        <p><label for="inputUsername" class="form-label visually">{{f.label}}:</label> {{ f }}</p>
    </div>
    <div class="alert-danger">{{ f.errors }}</div>
    {% endfor %}
 
    <p ><button type="submit" class="btn btn-primary">Сбросить по E-mail</button></p>
</form>
</div>
</div>
                </div>
            </div>
</div>

{% endblock %}

tytrip/users/templates/users/profile.html
{% extends 'base_new.html' %}
{% block header %}
    {% include 'trip/includes/header_new.html' %}
{% endblock %}
 
{% block content %}
  <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="row justify-content-center">
                        <div class="col-6">

<h1>Профиль</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if user.photo %}
    <p ><img src="{{ user.photo.url }}">
    {% else %}
    <p ><img class='poster' src="{{ default_image }}">
    {% endif %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <div class="md-form mb-0"><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</div>
    <div class="form-error">{{ f.errors }}</div>
    <br>
    {% endfor %}
    <p ><button type="submit" class="btn btn-primary">Сохранить</button></p>
    <hr>
    {% if not perms.users.social_auth %}
        <p><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
    {% endif %}
</form>
                        </div>
                    </div>
                </div>
            </div>
  </div>

{% endblock %}

tytrip/users/templates/users/register.html
{% extends 'base_new.html' %}
{% block header %}
    {% include 'trip/includes/header_new.html' %}
{% endblock %}
 
{% block content %}
    <section class="my-registration-form">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <!--    ЭТО ХЛЕБНЫЕ КРОШКИ -->
                    <nav aria-label="breadcrumb" class="my-4">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Форма регистрации</li>
                        </ol>
                    </nav>

                    <div class="row justify-content-center">
                        <div class="col-6">
                            <p class="lead">Для регистрации укажите имя пользователя, email и пароль</p>
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}
                                <form method="post" action="{% url 'users:register' %}">
                                    {% csrf_token %}
                                    <div class="mb-3">
                                        <label for="inputUsername" class="form-label visually-hidden">Имя пользователя</label>
                                        {{ form.username }}
                                    </div>
                                    <div class="mb-3">
                                        <label for="inputPassword" class="form-label visually-hidden">Пароль</label>
                                        {{ form.password1 }}
                                    </div>
                                    <div class="mb-3">
                                        <label for="ReInputPassword" class="form-label visually-hidden">Повторите пароль</label>
                                        {{ form.password2 }}
                                    </div>
                                    <div class="mb-3">
                                        <label for="ReInputPassword" class="form-label visually-hidden">email</label>
                                        {{ form.email }}
                                    </div>
                                    <div class="mb-3">
                                        <label for="ReInputPassword" class="form-label visually-hidden">first-name</label>
                                        {{ form.first_name }}
                                    </div>
                                    <div class="mb-3">
                                        <label for="ReInputPassword" class="form-label visually-hidden">last-name</label>
                                        {{ form.last_name }}
                                    </div>
                                    <button type="submit" class="btn btn-primary">Регистрация</button>
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

tytrip/users/templates/users/register_done.html
{% extends 'base_new.html' %}
 
{% block content %}
<main class="main">
<h1>Добро пожаловать!</h1>
 
<p >Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по этой <a href="{% url 'users:login' %}">ссылке</a>
</p>
</main>
{% endblock %}