tytrip/trip/urls.py
from django.urls import path, register_converter
from . import views
from . import  converters
from .views import SearchResultsView, SignUpView, SignInView, log_out, PostDetailView, FeedBackView, SuccessView, \
    TagView

register_converter(converters.FourDigitYearConverter, "year4")

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    # path('about/', views.about, name='about'),
    # path('topics/<slug:topic_slug>/', views.TopicsListView.as_view(), name='topics'),
    path('addpage/', views.AddPage.as_view(), name='add_page'),
    # path('contact_old/', views.ContactFormView.as_view(), name='contact_old'),
    # path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    # path('tag/<slug:tag_slug>/', views.TagsListView.as_view(), name='tag'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(), name='edit_page'),
    path('delete/<slug:slug>/', views.DeletePage.as_view(), name='delete_page'),

    # path('signup/', SignUpView.as_view(), name='signup'),
    # path('signin/', SignInView.as_view(), name='signin'),
    # path('logout/', log_out, name='logout',),
    path('post/<slug>/', PostDetailView.as_view(), name='post_detail'),
    path('contact/', FeedBackView.as_view(), name='contact'),
    path('contact/success/', SuccessView.as_view(), name='success'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('tag/<slug:slug>/', TagView.as_view(), name="tag"),
]

tytrip/tytrip/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.decorators.cache import cache_page
from rest_framework import routers

from trip.sitemaps import PostSitemap
from trip.views import page_not_found, TripViewSet
from . import settings
from django.contrib.sitemaps.views import sitemap
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

sitemaps = {'posts': PostSitemap}

router = routers.SimpleRouter()
router.register(r'triplist', TripViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trip.urls')),
    path('users/', include('users.urls', namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),
    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Администрирование сайта tytrip.ru"

tytrip/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.messages import success
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='users:login'), name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view(template_name = "users/password_reset_form.html",
                                   email_template_name = "users/password_reset_email.html",
                                   success_url = reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                                                              success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    ]

tytrip/trip/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail, BadHeaderError
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse, HttpResponseNotFound, Http404, HttpResponseRedirect, \
    HttpResponsePermanentRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.template.defaultfilters import slugify
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from datetime import datetime

from django.views import View
from django.views.generic import ListView, DetailView, FormView, CreateView, UpdateView, DeleteView
from rest_framework import generics, viewsets
from rest_framework.authentication import TokenAuthentication
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAdminUser
from rest_framework.response import Response
from taggit.models import Tag

from tytrip.settings import DEFAULT_FROM_EMAIL
from .forms import AddPostForm, UploadFileForm, ContactForm, CommentForm, SignUpForm, SignInForm, FeedBackForm
from .models import Trip, Topics, TagPost, Comment
from .permissions import IsAdminOrReadOnly
from .serializers import TripSerializer
from .utils import DataMixin



# Create your views here.

class IndexView(DataMixin, ListView):
    # model = Trip
    template_name = 'trip/index_new.html'
    context_object_name = 'posts'
    queryset = Trip.published.all().select_related('topic').prefetch_related('tags')
    # def get_queryset(self):
    #     return Trip.published.all().select_related('topic').prefetch_related('tags')
    extra_context = {
        'title': 'Главная страница',
        'newest_posts': queryset.order_by('-time_create')[:3],
        }


class AddPage(LoginRequiredMixin, CreateView):
    model = Trip
    fields = ['title', 'slug', 'image', 'content', 'tag']
    # form_class = AddPostForm
    template_name = 'trip/addpage.html'
    success_url = reverse_lazy('home')
    extra_context = {
        'title': 'Добавить статью',
    }
    # permission_required = 'trip.add_trip'
    # login_url = '/admin/'

    def form_valid(self, form):
        w = form.save(commit=False)
        w.author = self.request.user
        return super().form_valid(form)


class UpdatePage(PermissionRequiredMixin, UpdateView):
    model = Trip
    fields = ['title', 'slug', 'image', 'content', 'tag']
    template_name = 'trip/addpage.html'
    success_url = reverse_lazy('home')
    extra_context = {
        'title': 'Редактирование статьи',
    }
    permission_required = 'trip.change_trip'


class DeletePage(PermissionRequiredMixin, DeleteView):
    model = Trip
    fields = ['title', 'slug', 'image', 'content', 'tag']
    template_name = 'trip/addpage.html'
    success_url = reverse_lazy('home')
    extra_context = {
        'title': f'Удаление статьи:',
    }
    permission_required = 'trip.delete_trip'

def handle_uploaded_file(f):
    with open(f"uploads/{f.name}", "wb+") as destination:
        for chunk in f.chunks():
            destination.write(chunk)

@login_required
def about(request):
    if request.method == "POST":
        # handle_uploaded_file(request.FILES['file_upload'])
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(form.cleaned_data['file'])
    else:
        form = UploadFileForm()
    data = {
        'title': 'Upload file',
        'form': form,}
    return render(request, 'trip/about.html', context=data)


class TopicsListView(DataMixin, ListView):
    template_name = 'trip/index.html'
    context_object_name = 'posts'
    # allow_empty = False

    def get_queryset(self):
        return Trip.published.filter(topic__slug=self.kwargs['topic_slug']).select_related('topic').prefetch_related('tags')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        topic = get_object_or_404(Topics, slug=self.kwargs['topic_slug'])
        context['title'] = 'Тема - ' + topic.name
        context['newest_posts'] = *self.get_queryset().order_by('-time_create')[:3],
        return context


class ShowPost(DetailView):
    # model = Trip
    template_name = 'trip/post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        return get_object_or_404(Trip.published, slug=self.kwargs[self.slug_url_kwarg])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title # self.get_object().title
        return context


class TagsListView(DataMixin, ListView):
    template_name = 'trip/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Trip.published.filter(tags__slug=self.kwargs['tag_slug']).select_related('topic').prefetch_related('tags')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = get_object_or_404(TagPost, slug=self.kwargs['tag_slug'])
        context['title'] = 'Тег - ' + tag.tag
        context['newest_posts'] = *self.get_queryset().order_by('-time_create')[:3],
        return context

class ContactFormView(LoginRequiredMixin, DataMixin, FormView):
    form_class = ContactForm
    template_name = 'trip/contact.html'
    success_url = reverse_lazy('home')
    title_page = "Обратная связь"

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

################### alternative-views ###########################
class MainView(View):
    def get(self, request, *args, **kwargs):
        posts = Trip.objects.all().order_by('-time_create')
        paginator = Paginator(posts, 6)

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(request, 'trip/index.html', context={
            'page_obj': page_obj
        })


class PostDetailView(View):
    def get(self, request, slug, *args, **kwargs):
        post = get_object_or_404(Trip, slug=slug)
        common_tags = Trip.tag.most_common()
        last_posts = Trip.published.all().order_by('-id')[:5]
        comment_form = CommentForm()
        return render(request, 'trip/post_detail.html', context={
            'post': post,
            'common_tags': common_tags,
            'last_posts': last_posts,
            'comment_form': comment_form
        })

    def post(self, request, slug, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            text = request.POST['text']
            username = self.request.user
            post = get_object_or_404(Trip, slug=slug)
            Comment.objects.create(post=post, username=username, text=text)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
        return render(request, 'trip/post_detail.html', context={
            'comment_form': comment_form
        })


class SignUpView(View):
    def get(self, request, *args, **kwargs):
        form = SignUpForm()
        return render(request, 'trip/signup.html', context={'form': form})

    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')
        return render(request, 'trip/signup.html', context={'form': form})


class SignInView(View):
    def get(self, request, *args, **kwargs):
        form = SignInForm()
        return render(request, 'trip/signin.html', context={
            'form': form,
        })

    def post(self, request, *args, **kwargs):
        form = SignInForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                form.add_error(None, "Неправильный пароль или указанная учётная запись не существует!")
                return render(request, "trip/signin.html", {"form": form})
        return render(request, 'trip/signin.html', context={
            'form': form,
        })


def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


class FeedBackView(View):
    def get(self, request, *args, **kwargs):
        form = FeedBackForm()
        return render(request, 'trip/contact_new.html', context={
            'form': form,
            'title': 'Написать мне'
        })

    def post(self, request, *args, **kwargs):
        form = FeedBackForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            from_email = DEFAULT_FROM_EMAIL # form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message'] + '\n' + form.cleaned_data['email']
            try:
                send_mail(f'От {name} | {subject}', message, from_email, ['tgnudev@gmail.com',])
            except BadHeaderError:
                return HttpResponse('Невалидный заголовок')
            return HttpResponseRedirect('success')
        return render(request, 'trip/contact_new.html', context={
            'form': form,
            'title': 'Написать мне',
        })


class SuccessView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'trip/success.html', context={
            'title': 'Спасибо'
        })


class SearchResultsView(View):

tytrip/trip/templates/trip/includes/aside.html
<div class="col-md-4">
    <div class="card my-4">
        <h5 class="card-header">Теги</h5>
        <div class="card-body">
            <div class="d-flex flex-wrap">
                {% for mt in common_tags %}
                    <a href="{% url 'tag' mt.slug %}" class="m-3 h5 text-primary">#{{mt}}</a>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="card my-4">
        <h5 class="card-header">Последние статьи</h5>
            {% for lp in last_posts %}
                <div class="card-body">
                    <h5 class="card-title">{{ lp.title }}</h5>
                    {% if lp.image %}
                    <img src="{{ lp.image.url }}" alt="" class="card-img-top">
                    {% endif %}
                    {{ lp.content|safe|truncatechars:100 }}
                    <a href="{% url 'post_detail' lp.slug%}" class="card-link">Подробнее</a>
                    <hr>
                </div>
            {% endfor %}
    </div>
</div>

tytrip/trip/templates/trip/includes/aside_old.html
 <aside class="aside">
     {% include 'trip/includes/last_post_list.html'%}
    <div class="find">
      <input type="search" class="field" placeholder="Найти..." required>
      <button type="submit" class="button_search"></button>
    </div>
    <div class="mailing">
      <header class="header__aside">Рассылка</header>
      <form class="form">
        <input type="email" class="field-email" placeholder="Ваш email-адрес" required></intup>
      <button type="submit" class="button_email">Подписаться</button>
      </form>
    </div>
     {% show_all_tags %}

     {% show_topics topic_selected %}

  </aside>

tytrip/trip/templates/trip/includes/comments.html
{% load static %}
<div class="card my-4">
    <h5 class="card-header">Прокомментируй:</h5>
    <div class="card-body">
        {% if user.is_authenticated %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ comment_form.text }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
        {% else %}
            <h6 class="card-body"><a href="{% url 'users:login' %}">Авторизуйтесь</a> или <a href="{% url 'users:register' %}">зарегистрируйтесь</a> чтобы оставить комментарий</h6>
        {% endif %}
    </div>
</div>
{% if user.is_authenticated %}
{% for comment in post.comments.all %}
<div class="d-flex">
    <div class="flex-shrink-0">
        <img class="rounded-circle" src="https://placehold.co/50x50?text=user" alt="">
    </div>
    <div class="flex-grow-1 ms-3">
        <h5 class="mt-0">{{comment.username}}</h5>
        {{comment.text}}
    </div>
</div>
{% endfor %}
{% endif %}

tytrip/trip/templates/trip/includes/footer.html
<section class="my-footer mt-3">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="python" viewBox="0 0 16 16">
        <path fill-rule="evenodd"
          d="M14 4.5V14a2 2 0 0 1-2 2H7v-1h5a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5L14 4.5ZM0 11.85h1.6c.289 0 .533.06.732.179.201.117.355.276.46.477.105.201.158.427.158.677 0 .25-.054.476-.16.677-.106.199-.26.357-.464.474a1.452 1.452 0 0 1-.732.173H.79v1.342H0V11.85Zm2.06 1.714a.795.795 0 0 0 .085-.381c0-.227-.062-.4-.185-.521-.123-.122-.294-.182-.513-.182H.788v1.406h.66a.794.794 0 0 0 .374-.082.574.574 0 0 0 .238-.24Zm2.963.75v1.535H4.23v-1.52L2.89 11.85h.876l.853 1.696h.032l.856-1.696h.855l-1.339 2.464Z" />
      </symbol>
      <symbol id="telegram" viewBox="0 0 16 16">
        <path
          d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z" />
      </symbol>
    </svg>
    <div class="container">
      <div class="row">
        <div class="col-lg-9 col-sm-12 my-3">
          <a href="/" class="text-body-secondary text-decoration-none lh-1">
            <svg class="bi" width="30" height="24">
              <use xlink:href="#python" />
            </svg>
          </a>
          <span class="text-body-secondary">&copy; 2024 tytrip.ru </span>
        </div>
        <div class="col-lg-3 col-sm-12 my-3 d-flex justify-content-end">
          <ul class="nav list-unstyled">
            <li class=""><a class="text-body-secondary" href="https://web.telegram.org/"><svg class="bi" width="24"
                  height="24">
                  <use xlink:href="#telegram" />
                </svg></a></li>
            <li class="ms-2"><a class="text-end" href="#">Наверх</a></li>
          </ul>
        </div>
      </div>
    </div>
  </section>

tytrip/trip/templates/trip/includes/header.html
{% load static %}

<header class="header">
  <div class="container">
    <div class="menu">
      <a href="{% url 'home' %}" class="logo">
      <img src="{% static 'trip/images/noemi-logo.svg' %}" class="header-logo" alt="header-logo">
      </a>
      <nav class="head-menu">
            <ul class="menu-list">
                {% for item in menu %}
                    <li class="menu-list-item">
                        <a class="menu-link" href="{% url item.url_name %}">{{item.title}}</a>
                    </li>
                {% endfor %}
                {% if user.is_authenticated %}
                    <li class="menu-list-item"> <a class="menu-link" href="{% url 'users:profile' %}">{{user.username}}</a> | <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button type="submit">Выйти</button>
                    </form>
                    </li>
                {% else %}
                    <li class="menu-list-item"><a class="menu-link" href="{% url 'users:login' %}">Войти</a> | <a class="menu-link" href="{% url 'users:register' %}">Регистрация</a></li>
                    {% endif %}
            </ul>
      </nav>
    </div>
    <h1 class="header-title">Путешествие начинается здесь ...</h1>
  </div>
</header>

tytrip/trip/templates/trip/includes/header_new.html
{% load static %}
<section class="my-carousel">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active" style="background-color: #343a40!important">
            <div class="carousel-caption d-none d-md-block">
                              <script async src="https://tp.media/content?trs=383037&shmarker=601099&locale=ru&powered_by=true&border_radius=5&color_background=%23ffffff&color_border=%23fed42b&color_button=%23fed42b&promo_id=7339&campaign_id=193" charset="utf-8"></script>
                <h1>
<!--                  {% if post.title %}-->
<!--                    {{ post.title }}-->
<!--                  {% else %}-->
<!--                    {{ title }}-->
<!--                  {% endif %}-->
                </h1>
            </div>
        </div>
    </div>
  </div>
</section>

tytrip/trip/templates/trip/includes/last_post_list.html
{% if newest_posts %}
<div class="new__posts">
      <header class="header__aside">новые посты</header>
        {% for p in newest_posts %}
        <div class="posts">
          <div class="card">
            {% if p.image %}
                <img class="poster-mini" src="{{ p.image.url }}" alt="nice picture">
            {% endif %}
            <article class="article_post">
                <p><time class="time">{{p.time_create|date:"d-m-Y"}}</time></p>
                <a class="title-link-aside" href="{{ p.get_absolute_url }}">{{p.title}}</a>
            </article>
          </div>
        </div>
      {% endfor %}
</div>
{% endif %}

tytrip/trip/templates/trip/includes/list_tags.html
<div class="tags">
    {% if tags %}
      <header class="header__aside">Теги</header>
      <div class="tags_block">
                {% for t in tags %}
                <div class="tags_block_name">
                    <a class="tags_block_link" href="{{t.get_absolute_url}}">{{t.tag}}</a>
                </div>
                {% endfor %}
      </div>
    {% endif %}
</div>

tytrip/trip/templates/trip/includes/nav.html
<nav>
         <a href="#">Актрисы</a> |
         <a href="#">Певицы</a> |
         <a href="#">Спортсменки</a>
</nav>

tytrip/trip/templates/trip/includes/navbar.html
<section class="my-navigation">
  <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
      <a href="{% url 'home' %}" class="navbar-brand">
        <img
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Antu_flightgear.svg/512px-Antu_flightgear.svg.png?20160706104033"
          width="30" height="30" alt="">
      </a>
      <button class="btn btn-outline-success me-2" id="theme-toggle">🌙 Темная тема</button>
      <!--              <a href="{% url 'home' %}" class="navbar-brand">-->
      <!--                  <img src="https://upload.wikimedia.org/wikipedia/commons/a/ae/Nuxt_logo.svg" width="30" height="30" alt="NuxtJS">-->
      <!--              </a>-->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if request.get_full_path == '/' %}
          <a class="nav-link active" href="{% url 'home' %}">Главная</a>
          {% else %}
          <a class="nav-link" href="{% url 'home' %}">Главная</a>
          {% endif %}
          <a class="nav-link" href="{% url 'contact' %}">Контакты</a>
          <a class="nav-link" href="{% url 'add_page' %}">Добавить статью</a>
        </div>
        <form action="{% url 'search_results' %}" method="get" class="d-flex" role="search">
          <input name="q" class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск">
          <button class="btn btn-outline-success me-2" type="submit">Найти</button>
        </form>
        {% if user.is_authenticated %}
        <a class="btn btn-outline-light me-2" href="{% url 'users:profile' %}">{{user.username}}</a>
        <!--                        <a href="{% url 'logout' %}" class="btn btn-outline-light">Выход</a>-->
        <form method="post" action="{% url 'users:logout' %}">
          {% csrf_token %}
          <button class="btn btn-outline-light" type="submit">Выйти</button>
        </form>
        {% else %}
        {% if request.get_full_path == '/users/login/' %}
        <a href="{% url 'users:login' %}" class="btn btn-outline-light me-2 active">Войти</a>
        {% else %}
        <a href="{% url 'users:login' %}" class="btn btn-outline-light me-2">Войти</a>
        {% endif %}
        {% if request.get_full_path == '/users/register/' %}
        <a href="{% url 'users:register' %}" class="btn btn-outline-light me-2 active">Регистрация</a>
        {% else %}
        <a href="{% url 'users:register' %}" class="btn btn-outline-light me-2">Регистрация</a>
        {% endif %}
        {% endif %}
      </div>
    </div>
  </nav>
</section>

tytrip/trip/templates/trip/includes/search_form.html
{% load static %}
<section class="my-carousel">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active" style="background-color: #343a40!important">
            <div class="carousel-caption d-none d-md-block">
                <form action="{% url 'search_results' %}" method="get" class="my-2 my-lg-0">
                    <input name="q" type="text" class="form-control" placeholder="Поиск" aria-label="Поиск">
                    <button class="btn btn-outline-success mt-3" type="submit">Поиск</button>
                </form>
            </div>
        </div>
    </div>
  </div>
</section>

tytrip/trip/templates/trip/includes/topic_list.html
 <div class="topics">
      <header class="header__aside">Темы</header>
        <ul class="topic_block_ul">
            {% for topic in topics %}
            <div class="topics_block_name">
                     {% if topic.id == topic_selected %}
                             <li class="topic_block_link selected">{{topic.name}}
                                 <a class="topic_block_link_number" href="{{ topic.get_absolute_url }}">{{topic.posts.count}}</a>
                             </li>
                     {% else %}
                             <li class="topic_block_link">
                                 <a class="topic_block_link" href="{{ topic.get_absolute_url }}">{{topic.name}}</a>
                                 <a class="topic_block_link_number" href="{{ topic.get_absolute_url }}">{{topic.posts.all.count}}</a>
                             </li>
                     {% endif %}
            </div>
            {% endfor %}
        </ul>
 </div>